### PR TITLE
Fix Clang warnings by using proper function prototypes in macros

### LINKED ISSUE #178: Fix clang/gcc warnings
### Generated by Generative AI

_No response_

### Operating System:

Ubuntu

### ROS version or commit hash:

Rolling (latest)

### RMW implementation (if applicable):

_No response_

### RMW Configuration (if applicable):

_No response_

### Client library (if applicable):

_No response_

### 'ros2 doctor --report' output

_No response_

### Steps to reproduce issue

1. Build `tracetools` using the current `rolling` branch with clang and libc++:
    ```
    $ colcon build --packages-up-to tracetools --mixin clang-libcxx --cmake-args -DCMAKE_BUILD_TYPE=Debug
    ```
    * See the build command in the CI job here: https://ci.ros2.org/view/nightly/job/nightly_linux_clang_libcxx/1860/consoleFull#console-section-12.
        * The latest nightly_linux_clang_libcxx job is: https://ci.ros2.org/view/nightly/job/nightly_linux_clang_libcxx/2260/. You can see here that there are still warnings in `tracetools`: https://ci.ros2.org/view/nightly/job/nightly_linux_clang_libcxx/2260/clang/
    * This section in the ROS 2 docs also explains how to build with clang, but it doesn't cover building with libc++: https://docs.ros.org/en/rolling/Installation/Alternatives/Ubuntu-Development-Setup.html#clang.
1. Check the build output for `tracetools` and see if warnings are reported

### Expected behavior

No issues/warnings

### Actual behavior

There are some issues reported by clang, see https://github.com/ros2/ros2_tracing/pull/115.

Some of those issues may have been fixed since that PR was opened over a year ago.

### Additional information

After confirming that there are warnings, try to fix them. Look at the changes in #115.

After fixing the warnings, re-build and confirm that the warnings disappeared.

### PR DESCRIPTION
**Pull request by ShravanDeva5327**
This PR updates the macros to specify (void) in argument lists for functions that take no arguments. This resolves warnings from
Clang(-Wstrict-prototypes).

Tested locally with Clang; no build issues observed.

Closes https://github.com/ros2/ros2_tracing/issues/178
Supersedes https://github.com/ros2/ros2_tracing/pull/115

### CODE REVIEW

**Review by fujitatomoya — COMMENTED** [review]
@ShravanDeva5327 change looks good to me, but DCO is missing. can you address that?

**Comment by ShravanDeva5327** [comment]
@fujitatomoya I forgot to sign off the commit. I've added it now.

File: tracetools/include/tracetools/tracetools.h [hunk 1]
```diff
@@ -103,7 +103,7 @@
  * This is the preferred method over calling the underlying function directly.
  */
 #  define TRACETOOLS_TRACEPOINT_ENABLED(event_name) \
-  ros_trace_enabled_ ## event_name()
+  ros_trace_enabled_ ## event_name(void)
```
Comment (christophebedard) [inline tracetools/include/tracetools/tracetools.h]: I think it's the same issue as in #115: the `TRACETOOLS_TRACEPOINT_ENABLED` macro (defined here) is used by the instrumented packages to call the underlying function, which means it will use `...(void)` in the function call, which doesn't work. This will lead to a build failure in an instrumented package that uses the macro, like `rclcpp` (see build failures in the GitHub CI jobs or the Rpr job), so building `tracetools` only won't show the build error.

However, since the actual function is _declared_ by another macro (above in `tracetools.h`) and you added the `(void)` there, and since we don't need the `(void)` in the function _definition_ (in the
`DEFINE_TRACEPOINT` macro in `tracetools.c`), I think we don't need to change this line.

Does that make sense? You could try building up to `test_tracetools` (since that will include `rclcpp`) to validate.

**Comment by christophebedard** [comment]
By the way, it's good practice to reference any relevant issue or PR in the PR description. This way, reviewers can get the whole context behind a change. This also applies when creating issues, of course.

In this case, since this PR supersedes #115 (and since my comments on that PR may be relevant for this PR), it would be good to include "Supersedes #115" on a separate line in the PR description.

File: tracetools/include/tracetools/tracetools.h (hunk 1 above)
Comment (ShravanDeva5327) [reply tracetools/include/tracetools/tracetools.h]: with the current changes the following code
```
  /opt/ros/rolling/include/rclcpp/rclcpp/any_service_callback.hpp:196:13: error: expected primary-expression before ‘void’
    196 |         if (TRACETOOLS_TRACEPOINT_ENABLED(rclcpp_callback_register)) {
        |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ```
 
 expands to:
 ```
 if (tracetools_tracepoint_enabled_rclcpp_callback_register(void)) {
```
and passing void as an argument to function call is invalid, hence the build failure, Am I getting this correct??

**Comment by ShravanDeva5327** [comment]
> By the way, it's good practice to reference any relevant issue or PR in the PR description. This way, reviewers can get the whole context behind a change. This also applies when creating issues, of course.
> 
> In this case, since this PR supersedes #115 (and since my comments on that PR may be relevant for this PR), it would be good to include "Supersedes #115" on a separate line in the PR description.

That makes sense, I’ve edited the PR description, and I’ll make sure to reference related issues or PRs in the future too

**Comment by christophebedard** [comment]
Oh, and you can also include "Closes #178" in the PR description (again on a separate line). This way, the #178 issue will automatically get closed when this PR gets merged!

File: tracetools/include/tracetools/tracetools.h (hunk 1 above)
Comment (christophebedard) [reply tracetools/include/tracetools/tracetools.h]: it actually expands to `if (ros_trace_enabled_rclcpp_callback_register(void)) {`, but yes pretty much!

Just to summarize, there are 3 situations where some of these macros might be used:

1. Function declaration/prototype (in a header/`.h` file): this one needs to use `(void)` if the function takes no parameters. This is what the clang warnings are complaining about.
2. Function definition (in a `.c` file): this one does not technically need `(void)`, but it looks like we do use it in some places.
3. Function call (in an instrumented package, like `rclcpp`): this one should not use `(void)`, otherwise it results in a build error.

The `TRACETOOLS_TRACEPOINT_ENABLED` macro here in `tracetools.h` is used for (2) and (3), so we can't use `(void)`. It's a bit of a mess (typical C macros mess), but given all the repetitive code that we need for tracepoints and instrumentation functions, it's the best solution currently!

Comment (ShravanDeva5327) [reply tracetools/include/tracetools/tracetools.h]: Got it, is this good to go now??

File: tracetools/include/tracetools/tracetools.h [hunk 2]
```diff
@@ -46,20 +46,20 @@
 
 // *INDENT-OFF*
 #  define _TRACEPOINT_NOARGS(event_name) \
-  (ros_trace_ ## event_name)()
+  (ros_trace_ ## event_name)(void)
 #  define _TRACEPOINT_ARGS(event_name, ...) \
   (ros_trace_ ## event_name)(__VA_ARGS__)
 #  define _DO_TRACEPOINT_NOARGS(event_name) \
-  (ros_trace_do_ ## event_name)()
+  (ros_trace_do_ ## event_name)(void)
```
Comment (christophebedard) [inline tracetools/include/tracetools/tracetools.h]: I think there's a similar issue here: if I build up to `test_tracetools` with default options (so using gcc instead of clang, but I'm assuming the same thing happens with clang), I get a build error in `rclcpp`:

```
Starting >>> rclcpp
--- stderr: rclcpp                                                                          
In file included from /home/christophe.bedard/ros2_ws/src/ros2/rclcpp/rclcpp/include/rclcpp/service.hpp:35,
                 from /home/christophe.bedard/ros2_ws/src/ros2/rclcpp/rclcpp/include/rclcpp/callback_group.hpp:28,
                 from /home/christophe.bedard/ros2_ws/src/ros2/rclcpp/rclcpp/include/rclcpp/any_executable.hpp:20,
                 from /home/christophe.bedard/ros2_ws/src/ros2/rclcpp/rclcpp/include/rclcpp/memory_strategy.hpp:25,
                 from /home/christophe.bedard/ros2_ws/src/ros2/rclcpp/rclcpp/include/rclcpp/memory_strategies.hpp:18,
                 from /home/christophe.bedard/ros2_ws/src/ros2/rclcpp/rclcpp/include/rclcpp/executor_options.hpp:22,
                 from /home/christophe.bedard/ros2_ws/src/ros2/rclcpp/rclcpp/include/rclcpp/executor.hpp:38,
                 from /home/christophe.bedard/ros2_ws/src/ros2/rclcpp/rclcpp/src/rclcpp/executor.cpp:34:
/home/christophe.bedard/ros2_ws/src/ros2/rclcpp/rclcpp/src/rclcpp/executor.cpp: In member function ‘bool rclcpp::Executor::get_next_ready_executable(rclcpp::AnyExecutable&)’:
/home/christophe.bedard/ros2_ws/src/ros2/rclcpp/rclcpp/src/rclcpp/executor.cpp:776:3: error: expected primary-expression before ‘void’
  776 |   TRACETOOLS_TRACEPOINT(rclcpp_executor_get_next_ready);
      |   ^~~~~~~~~~~~~~~~~~~~~
gmake[2]: *** [CMakeFiles/rclcpp.dir/build.make:513: CMakeFiles/rclcpp.dir/src/rclcpp/executor.cpp.o] Error 1
gmake[2]: *** Waiting for unfinished jobs....
gmake[1]: *** [CMakeFiles/Makefile2:498: CMakeFiles/rclcpp.dir/all] Error 2
gmake: *** [Makefile:146: all] Error 2
---
Failed   <<< rclcpp [18.1s, exited with code 2]
```

I see the same failure in this GitHub CI job: https://github.com/ros2/ros2_tracing/actions/runs/15215810484/job/42800943159?pr=179#step:5:2925.

It's because `_TRACEPOINT_NOARGS` and `_DO_TRACEPOINT_NOARGS` are used by `TRACETOOLS_TRACEPOINT` and `TRACETOOLS_DO_TRACEPOINT` (indirectly through `_GET_MACRO_TRACEPOINT`/`_GET_MACRO_DO_TRACEPOINT`). `TRACETOOLS_TRACEPOINT` and `TRACETOOLS_DO_TRACEPOINT` are used both in `tracetools.c` to define functions _and_ by instrumented packages, which results in function calls with `(void)` and therefore fails the build (see above).

I think we have to create new macros just for the function name:

```
#  define _FUNC_TRACEPOINT(event_name) \
  (ros_trace_ ## event_name)
#  define _FUNC_TRACEPOINT_ENABLED(event_name) \
  (ros_trace_enabled_ ## event_name)
#  define _FUNC_DO_TRACEPOINT(event_name) \
  (ros_trace_do_ ## event_name)
```

and then those can be used by all other macros, where applicable, which also helps us avoid repeating the `ros_trace_* ## event_name` pattern in many locations. The macros that instrumented packages use should then not include `(void)`, and the macros to define functions in `tracetools.c` can use `(void)`.

File: tracetools/include/tracetools/tracetools.h (hunk 1 above)
Comment (christophebedard) [reply tracetools/include/tracetools/tracetools.h]: There's another issue unfortunately, see https://github.com/ros2/ros2_tracing/pull/179/files#r2105318848

File: tracetools/include/tracetools/tracetools.h (hunk 2 above)
Comment (ShravanDeva5327) [reply tracetools/include/tracetools/tracetools.h]: I think I'm getting this now, the macros `_TRACEPOINT_NOARGS / _DO_TRACEPOINT_NOARGS` are being used to define (in `tracetools.c`) / call (in instrumented packages) functions which are already declared, with void explicitly specified, by `_DECLARE_TRACEPOINT_NOARGS` macros in `tracetools.h`. So undoing changes to L49 and L53 should work. Also did you suggest creating new macros to solve this issue specifically or as a general improvement?

Comment (christophebedard) [reply tracetools/include/tracetools/tracetools.h]: I assumed that changing `_TRACEPOINT_NOARGS`/`_DO_TRACEPOINT_NOARGS` was required if we want to use `(void)` in the 2nd case described here https://github.com/ros2/ros2_tracing/pull/179#discussion_r2105211711, i.e., function definitions in `tracetools.c`. They use `TRACETOOLS_TRACEPOINT`/`TRACETOOLS_DO_TRACEPOINT`, which use `_TRACEPOINT_NOARGS`/`_DO_TRACEPOINT_NOARGS`. Since `_TRACEPOINT_NOARGS`/`_DO_TRACEPOINT_NOARGS` are used by `TRACETOOLS_TRACEPOINT`/`TRACETOOLS_DO_TRACEPOINT`, this means we can't just change them without adding `(void)` for the 3rd use-case described in https://github.com/ros2/ros2_tracing/pull/179#discussion_r2105211711. In that case, we'd have to create separate macros to be used for the function definitions in `tracetools.c`, without using the `TRACETOOLS_TRACEPOINT`/`TRACETOOLS_DO_TRACEPOINT` macros.

However, I think adding `(void)` for the 2nd use-case (function definition in `tracetools.c`) is not strictly necessary, so we could proceed with this. Did you check that there are no warnings reported by clang after your latest changes?

Comment (christophebedard) [reply tracetools/include/tracetools/tracetools.h]: > Did you check that there are no warnings reported by clang after your latest changes?

According to the latest nightly_linux_clang_libcxx job, it does complain about `-Wstrict-prototypes` in `tracetools.c`, although it's hard to tell which exact function it's complaining about. https://ci.ros2.org/view/nightly/job/nightly_linux_clang_libcxx/2266/clang/folder.106785574/

Comment (ShravanDeva5327) [reply tracetools/include/tracetools/tracetools.h]: >  Did you check that there are no warnings reported by clang after your latest changes?

Yes I did, and there were no warnings. also I used clang with `-Wstrict-prototypes` to compile a simple program
```cpp
// test.h
int foo(void);
```

```cpp
// test.c
#include "test.h"
int main(void) {
    foo();
    return 0;
}

int foo() {
    return 42;
}
```

this also didn't gave any warnings. So I assumed specifying `(void)` in function declaration is sufficient

Comment (christophebedard) [reply tracetools/include/tracetools/tracetools.h]: Got it. Then I'll manually trigger a nightly_linux_clang_libcxx job with your branch and we'll see. ci.ros2.org isn't very responsive; as soon as I can trigger it, I'll post a link to the job here.

Comment (christophebedard) [reply tracetools/include/tracetools/tracetools.h]: Here it is:

* nightly_linux_clang_libcxx [Build Status](https://ci.ros2.org/view/nightly/job/nightly_linux_clang_libcxx/2267/)

Comment (christophebedard) [reply tracetools/include/tracetools/tracetools.h]: It unfortunately does complain about `tracetools.c`: https://ci.ros2.org/view/nightly/job/nightly_linux_clang_libcxx/2267/clang/. Looking at the full warnings in the build output, it's definitely complaining about the function definitions: https://ci.ros2.org/view/nightly/job/nightly_linux_clang_libcxx/2267/console#console-section-163.

Comment (ShravanDeva5327) [reply tracetools/include/tracetools/tracetools.h]: In that case I'll just add new macros you suggested, not entirely sure why I was not getting those warnings locally though.

**Comment by ShravanDeva5327** [comment]
This should hopefully resolve the warnings. Since I'm not able to reproduce them locally, I can't confirm if they're fully resolved.

@christophebedard Could you please trigger the CI job manually to check?

File: tracetools/include/tracetools/tracetools.h (hunk 2 above)
Comment (christophebedard) [reply tracetools/include/tracetools/tracetools.h]: I think it might just be due to a different version of clang on Ubuntu 22.04 (which both of us are using) vs Ubuntu 24.04 (the actual target platform for Rolling). If I try in an Ubuntu 24.04 Docker container, I can indeed see the warnings that the CI job above reported. I used [`osrf/ros2:devel`](https://github.com/osrf/docker_images/blob/master/README.md#ros2--) and then followed the instructions to build ROS 2 from source, but I think using `osrf/ros2:source` might've allowed me to skip some of the source build steps.

It might be worth spending time setting up a proper Ubuntu 24.04 development environment using Docker (or just trying it out and making notes so that you can easily use it in the future) for these kinds of situations where Ubuntu 24.04 is needed/preferred.

File: tracetools/src/tracetools.c [hunk 3]
```diff
@@ -41,28 +41,28 @@
...
   { \
     _CONDITIONAL_TP(event_name); \
   } \
-  bool TRACETOOLS_TRACEPOINT_ENABLED(event_name) \
+  bool _FUNC_TRACEPOINT_ENABLED(event_name)(void) \
   { \
     return _CONDITIONAL_TP_ENABLED(event_name); \
   } \
-  void TRACETOOLS_DO_TRACEPOINT(event_name) \
+  void _FUNC_DO_TRACEPOINT(event_name)(void) \
```
Comment (christophebedard) [inline tracetools/src/tracetools.c:65]: It's a good call to use the `_FUNC_*` macros directly here! For some reason I was envisioning a much more complex and annoying solution using even more macros, so this is much simpler.

File: tracetools/include/tracetools/tracetools.h [hunk 4]
```diff
@@ -45,22 +45,28 @@
 #  define _GET_MACRO(_1, _2, _3, _4, _5, _6, _7, _8, _9, _10, NAME, ...) NAME
 
 // *INDENT-OFF*
+#  define _FUNC_TRACEPOINT(event_name) \
+  (ros_trace_ ## event_name)
+#  define _FUNC_TRACEPOINT_ENABLED(event_name) \
+  (ros_trace_enabled_ ## event_name)
+#  define _FUNC_DO_TRACEPOINT(event_name)\
```
Comment (christophebedard) [inline tracetools/include/tracetools/tracetools.h]: Very minor suggestion, for consistency:

```suggestion
#  define _FUNC_DO_TRACEPOINT(event_name) \
```

**Review by christophebedard — COMMENTED** [review]
I tried in an Ubuntu 24.04 Docker container and it seems like your new changes did the trick!

Here's a new job to validate that the warnings went away:

* nightly_linux_clang_libcxx [Build Status](https://ci.ros2.org/view/nightly/job/nightly_linux_clang_libcxx/2271/)

If that looks good, I'll run full CI after you apply my suggestion.

**Comment by christophebedard** [comment]
There seem to be weird issues with downloading from http://archive.ubuntu.com in the nightly_linux_clang_libcxx job. I retriggered it a second time.

**Comment by christophebedard** [comment]
..and I just remembered that I should use [ci_linux_clang_libcxx](https://ci.ros2.org/view/manual/job/ci_linux_clang_libcxx/) instead of nightly_linux_clang_libcxx for manually-triggered jobs :grimacing:

**Comment by christophebedard** [comment]
It failed once again due to an infrastructure issue. Here's a ci_linux_clang_libcxx job instead: 

* ci_linux_clang_libcxx [Build Status](https://ci.ros2.org/view/manual/job/ci_linux_clang_libcxx/83/)

**Comment by christophebedard** [comment]
That failed again due to issues connecting to archive.ubuntu.com. Let's just wait a bit.

File: tracetools/include/tracetools/tracetools.h (hunk 2 above)
Comment (ShravanDeva5327) [reply tracetools/include/tracetools/tracetools.h]: > It might be worth spending time setting up a proper Ubuntu 24.04 development environment using Docker

I was thinking of doing the same when I get a major issue, but I’ll just go ahead and do it now!

**Comment by ShravanDeva5327** [comment]
> That failed again due to issues connecting to archive.ubuntu.com. Let's just wait a bit.

Looks like the same issue is causing GitHub actions to fail

```
  Err:1 http://archive.ubuntu.com/ubuntu noble-updates/main amd64 libapparmor1 amd64 4.0.1really4.0.1-0ubuntu0.24.04.4
    Connection failed [IP: 91.189.91.82 80]
  Err:2 http://archive.ubuntu.com/ubuntu noble/main amd64 sudo amd64 1.9.15p5-3ubuntu5
    Connection failed [IP: 185.125.190.83 80]
  E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/a/apparmor/libapparmor1_4.0.1really4.0.1-0ubuntu0.24.04.4_amd64.deb  Connection failed [IP: 91.189.91.82 80]
  E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/s/sudo/sudo_1.9.15p5-3ubuntu5_amd64.deb  Connection failed [IP: 185.125.190.83 80]
  E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

**Comment by ahcorde** [comment]
* ci_linux_clang_libcxx [Build Status](https://ci.ros2.org/view/manual/job/ci_linux_clang_libcxx/85/)

**Review by christophebedard — APPROVED** [review]
Looks good to me now, thanks for iterating!

Now it's just about validating that this fixes the clang warnings (which I think it should) and then running full CI.

File: tracetools/include/tracetools/tracetools.h (hunk 2 above)
Comment (christophebedard) [reply tracetools/include/tracetools/tracetools.h]: Great. Let me know if you need help/tips. Tons of people have Docker-based ROS development environments, so there should be tons of resources out there.

**Comment by christophebedard** [comment]
The warnings indeed disappeared! https://ci.ros2.org/view/manual/job/ci_linux_clang_libcxx/85/clang/

Now I'll trigger full CI.

**Comment by christophebedard** [comment]
Pulls: ros2/ros2_tracing#179
Gist: https://gist.githubusercontent.com/christophebedard/21ac843a08ababb31d6b90d0dfdad86f/raw/17e9b7e0005b9df94c92e8d33f4cb5849e71ec2f/ros2.repos
BUILD args:  --packages-above-and-dependencies tracetools
TEST args:  --packages-above tracetools
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/16119
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/23813/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/17896/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/3231/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/24492/)

**Review by ahcorde — APPROVED** [review]
Thank you for fixing this!

**Comment by ahcorde** [comment]
https://github.com/Mergifyio backport kilted

**Comment by christophebedard** [comment]
> Thank you for fixing this!

Yes, thank you @ShravanDeva5327!

**Comment by ros-discourse** [comment]
This pull request has been mentioned on **Open Robotics Discourse**. There might be relevant details there:

https://discourse.openrobotics.org/t/gsoc-2025-improvements-to-ros-2-tracing/50062/1

**Comment by ros-discourse** [comment]
This pull request has been mentioned on **Open Robotics Discourse**. There might be relevant details there:

https://discourse.openrobotics.org/t/gsoc-2025-improvements-to-ros-2-tracing/50063/1
